{
            "Gig namn": self.name,
            "Pris": self.pris if not riggdag else 0,
            "Personal": self.personal,
            "extraPersonal": self.i_data.get('extraPersonal', 0),
            "Projekt timmar": self.gig_timmar*self.personal*len(self.dagar_list),
            "Rigg timmar": self.rigg_timmar*self.personal,
            "Totalt timmar": self.tim_budget,
            "Pryl pris": self.pryl_pris,
            "prylPaket": paket_id_list,
            "extraPrylar": pryl_id_list,
            "antalPrylar": antal_string,
            "antalPaket": antal_paket_string,
            "Projekt kanban": self.name,
            "Projekt": self.projekt,
            "börjaDatum": self.i_data["Börja datum"],
            "slutaDatum": self.i_data["Sluta datum"],
            "dagar": self.i_data["dagar"],
            "packlista": packlista,
            "restid": self.restid*self.personal*2,
            "projektTid": self.projekt_timmar*self.personal,
            "dagLängd": str(self.dag_längd),
            "slitKostnad": self.slit_kostnad,
            "prylFonden": self.pryl_fonden,
            "hyrthings": self.hyr_things,
            "avkastWithoutPris": self.avkastning,
            "avkast2": self.teoretisk_avkastning,
            "frilanstimmar": self.tim_budget_frilans,
            "total_tid_ex_frilans": self.tim_budget_personal,
            "frilans": self.frilans_lista,
            "ny proj ledare från uppdatera": [
                x for x in self.i_data.get("projektledare")
            ],  # Så jag kan göra lite logik
            "producent": [x for x in self.i_data.get("producent")],
            "leverans_nummer": leverans_nummer,
            "Kund": self.kund,
            "Svanis": self.svanis,
            "Typ": self.projekt_typ,
            "Adress": self.adress,
            "Beställare": self.bestallare,
            "input_id": self.i_data.get("input_id"),
            "made_by": [self.i_data.get("input_id")],
            "post_deadline": self.i_data.get("post_deadline"),
            "All personal": self.person_list,
            'slutkund_temp': self.slutkund,
            'role_format': self.make_format_for_roles(),
            'extra namn': self.extra_name,
            "OB": self.ob_text,
            "Kommentar från formulär": self.comment,

            #"typ person lista": [x for x in self.person_list]
            #"Mer folk": list(map(itemgetter("id"), self.specifik_personal))
        }